services:
  spese-api:
    build: .
    command: npm run start:dev
    restart: always
    ports:
      - 8082:8082
    env_file:
      - .env
    volumes:
      - .:/home/spese-api
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
