export enum ExpenseCategory {
  NA = 'NÃO INFORMADO',
  HEALTH = 'SAÚDE',
  LEISURE = 'LAZER',
  ACADEMIC = 'ACADÊMICO',
  FUN = 'DIVERSÃO',
  FOOD = 'COMIDA',
  HOME = 'CASA',
  CLOTHES = 'ROUPAS',
  PETS = 'PETS',
  UBER = 'UBER',
  INVESTIMENT = 'INVESTIMENTO',
  GYM = 'ACADEMIA',
}
