export const ASYNC_WORKER = {
  REDIS_STREAMS: {
    EXPENSE_CREATED: 'expense:created',
  },
  REDIS_GROUPS: {
    EXPENSE_CREATED: 'expense_created',
  },
  REDIS_ENTRY_IDS: {
    NEW_ENTRY: '*',
    LAST_ENTRY: '$',
    UNRECEIVED_ENTRY: '>',
    PENDING_ENTRY: '0-0',
  },
  ACK_SUCCESS: 1,
} as const;

export const DEPENDENCY_INJECTION_PROVIDERS = {
  ASYNC_WORKER_SUBSCRIBERS: 'ASYNC_WORKER_SUBSCRIBERS',
  EXTERNAL_OAUTH_PROVIDERS: 'EXTERNAL_OAUTH_PROVIDERS',
} as const;
